/* eslint-disable react/jsx-filename-extension */
import Head from 'next/head';
import PinList from '../../components/PinList';

export default function MyPins({ userId }) {
  return (
    <>
      <Head>
        <title>Pin Pics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PinList userId={userId} />
      </main>
    </>
  );
}
