/* eslint-disable react/prop-types, react/jsx-props-no-spreading */
import { config } from '@fortawesome/fontawesome-svg-core';
import Head from 'next/head';
import { SessionProvider } from 'next-auth/react';
import { dedupExchange, cacheExchange, fetchExchange } from 'urql';
import { withUrqlClient } from 'next-urql';

import '@fortawesome/fontawesome-svg-core/styles.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.css';

config.autoAddCss = false;

function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider session={pageProps.session}>
        <Component {...pageProps} />
      </SessionProvider>
    </>
  );
}

export default withUrqlClient((ssrExchange) => ({
  url: 'https://most.stepzen.net/api/apps/__graphql',
  exchanges: [dedupExchange, cacheExchange, ssrExchange, fetchExchange],
  fetchOptions: {
    headers: { authorization: 'Apikey most::stepzen.net+1000::809c7ed87aefa87e3a5cef8dab9059de96e754cb121a8ff2495bbfe1fbf65f98' },
  },
}))(App);
